### ISSUE TITLE
is it possible to have overrides for specific window types?

### ISSUE THREAD

**Issue by kupiqu** [tsujan/BreezeEnhanced#13]
could this be a feasible feature request/enhancement?

**Comment by tsujan** [comment]
Yes, of course!

It had been mentioned before but it may be needed to be implemented outside Breeze(Enhanced). Since I'm not sure yet, I leave this open.

**Comment by trmdi** [comment]
An idea from the past: https://github.com/tsujan/BreezeEnhanced/issues/1#issuecomment-427245556

> Can you make BreezeEnhanced's window-selection like the Kwin's one ? It lacks Window Role, Window type...
>
>![image](https://user-images.githubusercontent.com/11857205/46516496-2c5ff000-c894-11e8-96de-4b5ba9406df3.png)

**Comment by kupiqu** [comment]
Sorry @trmdi, missed that you mentioned this already

**Comment by tsujan** [comment]
It's good to have a separate issue for it.

FYI:

If you take a look at my other programs, you'll find that they are all purely based on Qt -- not on KDE -- so that, with them, I can do virtually anything I want (with a little exaggeration). Only BreezeEnhanced is at the mercy of KDE :( So, some things are out of my control -- or, at least, I think so for now.

**Comment by tsujan** [comment]
Sorry for the long delay! I was very busy with other projects but, at last, found time to look into this.

Window types can be covered but I think distinguishing between normal windows and dialogs is enough — covering other types would be an overkill. This is what I did here:

![dialog](https://user-images.githubusercontent.com/981076/57137788-226c8400-6dc6-11e9-9b0d-c5eb2ab65caa.png)

When "Only for dialogs" is checked (it's unchecked by default), the settings above it will be applied only to dialogs.

I tested it with QTerminal and it was effective. In the following screenshot, I've chosen a very dark color for QTerminal itself but given the color of Kvantum's KvCurves to its dialog:

![qterminal](https://user-images.githubusercontent.com/981076/57137888-69f31000-6dc6-11e9-9bf4-a551e650a32e.png)

The rule for qterminal dialog should be above the rule for its normal window because it should be checked before it.

@kupiqu, @trmdi Is this OK to you?

**Comment by tsujan** [comment]
OK, this is cool. I added this rule at the top:

![dialogs](https://user-images.githubusercontent.com/981076/57142830-bfcdb500-6dd2-11e9-8710-3a5c97237060.png)

Made a dialog color scheme for KvAmbience and now, dialogs have a nice title-bar:

![KvAmbience_dialog](https://user-images.githubusercontent.com/981076/57142898-e12ea100-6dd2-11e9-8ebb-2958933f74a1.png)

I'll go with it — will make a commit after testing it for a while.

**Comment by trmdi** [comment]
LGTM. Waiting for the commit. ;-)

**Comment by tsujan** [comment]
Done.

Made the commit sooner for it to be tested by more users. The changes were elementary.

Thanks for the good idea!

**Comment by kupiqu** [comment]
Looks great!

I guess I only miss the option to do the opposite, to apply the override only to the main window and not to the dialog.

**Comment by tsujan** [comment]
> to apply the override only to the main window and not to the dialog.

Add the overrides for the main window and then add a rule without override only for its dialogs above it (by just checking "Only for dialogs). I haven't tried that but I think it'll work.

**Comment by tsujan** [comment]
@kupiqu I tested my above-mentioned theory and it worked :)

All in all, current options are very flexible. The user just needs to how to use and sort them (the order of overrides is sometimes important). That's the case with KWin's custom title-bar colors too; so, those who have played with the latter know how to use the former.
