### ISSUE TITLE
Sharper Outline for active and inactive windows

### ISSUE THREAD

**Issue by ripefig** [tsujan/BreezeEnhanced#17]
See examples here.

https://github.com/kupiqu/SierraBreezeEnhanced/issues/12

This would improve the contrast and make it easier to tell the difference between active an inactive windows. It can just be a simple outline. A 3D look (created with two outlines) would be "nice", but not necessary.

**Comment by tsujan** [comment]
Thank you for the suggestion! But please also consider that:

(1) Inactive windows can be distinguished by their title-bars.

(2) Even if, for whatever reason, we don't see the title-bar, Kvantum themes can distinguish between active and inactive windows when they contain the required elements and colors. Several themes included in Kvantum do so. I forked the Breeze titlebar mainly for Kvantum ;)

(3) Since I should follow the Breeze titlebar code whenever it's updated and because my free time is taken by several purely Qt based projects, I need to keep the code differences manageable. So, probably apart from https://github.com/tsujan/BreezeEnhanced/issues/13, I don't want to add more codes. Actually, I haven't had time to think about https://github.com/tsujan/BreezeEnhanced/issues/13 either.

So, I close this not because your suggestion has any problem but for the above-mentioned reasons, especially (3).

**Comment by ripefig** [comment]
@tsujan Understood, thanks.

I would only note that your theme already has borders, they are just very feint and don't distinguish between active and inactive. Making the border darker relative to the titlebar would also look more professional with some of the Kvantum themes. It just looks a little incomplete with the feint border.
