### ISSUE TITLE
Top highlight not visible with dark colors

### ISSUE THREAD

**Issue by ripefig** [tsujan/BreezeEnhanced#22]
![image](https://user-images.githubusercontent.com/45201036/66270064-ef885980-e857-11e9-95b5-e1ff50750438.png)

**Comment by tsujan** [comment]
If the dark color is "#000", it shouldn't be visible because Qt can't make it lighter. Is it, in your case?

**Comment by ripefig** [comment]
Perhaps you can see it more clearly here: 
![image](https://user-images.githubusercontent.com/45201036/66272203-56653d00-e86f-11e9-9ce9-3007bd39f2f1.png)
I am talking about the faint light line at the top of titlebar. You can see it clearly on gray titlebars, but you can't see it at all if the titlebar is black.

**Comment by tsujan** [comment]
By using a color picker with your screenshot, I found that the color is really pitch black. `QColor::lighter` doesn't work with "#000". That's an old Qt issue. It has never been fixed; apparently, Qt devs don't see it as a bug!

BTW, pitch black isn't a good titlebar/window color because shadows won't be visible with it.
