### ISSUE TITLE
Active and inactive windows 

### ISSUE THREAD

**Issue by Da-Viper** [tsujan/BreezeEnhanced#29]
the Default breeze has the ability to change colours of the borders depending on if the window is active or not by going to 
~/.config/kdeglobals  under the group [WM] 

add the line 
frame=138,178,243
inactiveFrame=100,100,100 

restart  then it will show up in window 
 here is a picture of what i mean 

![Screenshot_20200915_114604](https://user-images.githubusercontent.com/57949090/93201397-0a8e6980-f749-11ea-9bd3-81bafe6dfed0.png)

could you add the ability to breeze enhanced too 
here it is also for other decoration like hello,lightly and sierra

![Screenshot_20200915_115049](https://user-images.githubusercontent.com/57949090/93201889-bafc6d80-f749-11ea-990c-3f1f9493b500.png)
thanks

**Comment by tsujan** [comment]
One of my reasons to fork the Breeze decoration was removing its "ugly" elements, especially when it was used with the Kvantum widget style. `ColorRole::Frame` in `breezedecoration.cpp` was among them. Since both Kvantum and GTK can distinguish between active and inactive windows, there was no need to an ugly inactive frame.

Of course, "ugliness" is a subjective term and tastes differ. I don't deny that what's ugly to me may be elegant to another person and vice versa. But BreezeEnhanced is understandably influenced by its developer's taste, to some extent.
