### ISSUE TITLE
Button with symbols

### ISSUE THREAD

**Issue by Mte90** [tsujan/BreezeEnhanced#4]
It is not clear to me how to configure to use the usual symbols for the close/minimize icons instead the colored circles.

**Comment by tsujan** [comment]
Uncheck the box "macOS-like buttons" and you'll have symbolic buttons, like in this screenshot:

![buttons](https://user-images.githubusercontent.com/981076/46534211-43163f00-c8b4-11e8-9df6-de53faed3a4e.png)

I added that checkbox last night because not all themes looked good with macOS buttons.

Please always use the latest git version!

**Comment by tsujan** [comment]
BTW, with the symbolic buttons, I've changed some symbols that didn't look elegant to me.

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/46535450-b9627380-c8ab-11e8-8ea5-87c746b6e5a6.png)
I don't have that check and I have updated and compiled yesterday night.
I updated now and compile, I will let you know.

**Comment by Mte90** [comment]
Ok now I have the setting :-)

**Comment by tsujan** [comment]
BreezeEnhanced was added to github only yesterday and was made only a few days ago. So, it'll be under heavy development. I added that checkbox last night and did some other works after it :) Please upgrade to the latest git version!

**Comment by tsujan** [comment]
Oh, don't forget to log out and log in again after upgrading! KDE is so tenacious ;)

**Comment by kupiqu** [comment]
I am relatively new using Mac style colors and, on hovering, I actually like small symbols overlaying the colors to remind me what colors are about.

Rarely, but still sometimes, get confused between green-maximize and orange-minimize color associations, and more frequently for other color associations, not currently implemented here ( yet ;) ), like cyan and lavender colors with keep above and show in all desktops, respectively, I guess because I'm less familiar with those. Sierrabreeze works that way, and I find it helpful. 

Do you think it would make sense to add that, as a disabled by default option perhaps?

**Comment by kupiqu** [comment]
If considered, I would suggest that for inactive windows, the symbols remain on top of the gray background (even without hovering). This is not how sierrabreeze works, but would find it much better (both in terms of looking and being more informative) in comparison to just 3+ gray circles in the titlebar...

**Comment by kupiqu** [comment]
Mmm, the gray circle could even be omitted entirely under this option, actually, which would look very nice... only recovering the full color on hovering, as described in #1

**Comment by tsujan** [comment]
@kupiqu

At some point, I'll add an option to show symbols with macOS buttons when they're under the cursor. I think that will solve your problem.

As for gray inactive buttons that are colorized on mouseover, I've done it here; will soon make a commit after some tests.

**Comment by kupiqu** [comment]
> As for gray inactive buttons that are colorized on mouseover, I've done it here; will soon make a commit after some tests.

Excellent!

> At some point, I'll add an option to show symbols with macOS buttons when they're under the cursor. I think that will solve your problem.

That is great, thanks!

For inactive windows, I'm still thinking what could be more informative while being minimalistic. To this regard, I'm wondering if you'd like to explore how these two options look like compared to plain gray backgrounds for the case they look better:

1. Remove gray backgrounds and use symbols instead, which get fully colored on hovering.
2. Replace gray backgrounds by non-filled, colored stroke circles, which get filled on hovering.

**Comment by tsujan** [comment]
I'm afraid removing the circles or using hollow ones would be an inconsistency in the design. Gray inactive circles look nice here; they also show the inactive state very well. My problem with them was only about distinguishing buttons from each other and it was solved by your suggestion at https://github.com/tsujan/BreezeEnhanced/issues/1#issuecomment-427369355

**Comment by kupiqu** [comment]
> For inactive windows, I'm still thinking what could be more informative while being minimalistic. To this regard, I'm wondering if you'd like to explore how these two options look like compared to plain gray backgrounds for the case they look better:
> 
> 1. Remove gray backgrounds and use symbols instead, which get fully colored on hovering.
> 2. Replace gray backgrounds by non-filled, colored stroke circles, which get filled on hovering.

FYI. I did sth following these lines for my personal use here: https://github.com/kupiqu/SierraBreezeEnhanced
