### ISSUE TITLE
[Feature request] Rounded corners

### ISSUE THREAD

**Issue by ericmacedo** [tsujan/BreezeEnhanced#44]
Is it possible to add rounded corners?

SierraBreezeEnhanced does have it, but I prefer BreezeEnhanced...

If so, how difficult would it be? 
I have some C++ knowledge. However, my KDE development skills are basically zero.

**Comment by tsujan** [comment]
The corners are already rounded as far as Breeze allows (e.g., if you remove the side and bottom borders, the top right and left corners will still be rounded slightly) — I even added codes to prevent blurring from going beyond such corners.

As I've mentioned in other places, I don't want more differences between the codes of BreezeEnhanced and Breeze because, otherwise, the process of upgrading by following the upstream changes would become not only time-consuming but also prone to errors/bugs, while I'm too busy to dedicate more time to BreezeEnhanced.

**Comment by thrdroom** [comment]
@ericmacedo

Use [https://github.com/matinlotfali/KDE-Rounded-Corners](https://github.com/matinlotfali/KDE-Rounded-Corners) on top of BreezeEnhanced for some nice rounded corners :large_blue_circle:
