### ISSUE TITLE
Button size: medium is blurred buttons compared to regular Breeze decorations

### ISSUE THREAD

**Issue by MirceaMx** [tsujan/BreezeEnhanced#6]
Compared to the regular Breeze decorations the buttons look blurred (no MacOS style) when chosen. Selecting the small size is OK but they are...well to small.
 See here for screenshots: https://imgur.com/a/xCnQjAh

**Comment by tsujan** [comment]
Here, the buttons are quite sharp:

![clear](https://user-images.githubusercontent.com/981076/47346443-15096b00-d6ba-11e8-8890-035a20d30f83.png)

It always depends on the button size you choose. That should be the case with Breeze too but it can't be seen with diagonal lines Breeze draws. For example, in your screenshot, the close buttons and question marks are the same in Breeze and BreezeEnhanced because they have no horizontal/vertical line.

If you make a 22-px sharp image with horizontal and vertical lines, it won't be sharp when its size is 16px because the grids are different for those sizes.

That being said, I'll see if they can be made sharp with all sizes. It means different drawings for different sizes and more code.

**Comment by MirceaMx** [comment]
I understand. Thank you.

**Comment by tsujan** [comment]
I looked into it. It's possible to have super sharp horizontal and vertical lines. However, since the button size may not be an integer, the shape may need to have an offset by less than 1 px to remain sharp. That may be seen only when it's inside the hover circle, like this:

![sharp](https://user-images.githubusercontent.com/981076/47368641-de9a1300-d6ee-11e8-8e41-ec320726fe9d.png)

I think it's acceptable; what do you think?

**Comment by MirceaMx** [comment]
The X button still seems to look blurry. Overall it's better.

**Comment by tsujan** [comment]
The x button is exactly that of Breeze and can't be made better because it has no horizontal or vertical line. The same is true for all shapes with diagonal or curved lines; they should be anti-aliased and that means some pixels should be neither black nor white.

**Comment by MirceaMx** [comment]
Ok. GREAT job.  Closing issue now.

**Comment by tsujan** [comment]
I'm afraid I had to reverse the commit about sharp lines because max and min buttons looked unnatural compared to other buttons, especially with large sizes.

Lesson leaned: Breeze devs are right; anti-aliasing is always needed and, when there are also diagonal lines, all lines should be a little blurry to look natural beside each other.
